spring:
  ai:
    ollama:
      chat:
        options:
          model: llama3.2:1b
      embedding:
        options:
          model: nomic-embed-text
server:
  port: 8081

app:
  pdf:
    path: classpath:/data/National_Bank_of_Cambodia_TCRMG_2026.pdf